# Generated by Django 3.0.7 on 2020-06-06 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='nex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_post', to='post.post'),
        ),
        migrations.AddField(
            model_name='post',
            name='previous',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_post', to='post.post'),
        ),
    ]
